# Generated by Django 5.1.2 on 2024-11-05 18:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0004_alter_cartmodel_when_added"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when_created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 11, 5, 18, 47, 59, 623906)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GET READY", "Getready"),
                            ("DELIVERED", "Delivered"),
                            ("READY", "Ready"),
                            ("PAYED", "Payed"),
                        ],
                        default="GET READY",
                        max_length=45,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.cartmodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-when_created_at"],
            },
        ),
    ]
