# Generated by Django 5.1.2 on 2024-11-05 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_service", "0002_alter_ordermodel_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="when_created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 5, 18, 50, 3, 121569)
            ),
        ),
    ]
