# Generated by Django 5.1.2 on 2024-11-05 18:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_cartmodel_when_added"),
        ("order_service", "0003_alter_ordermodel_when_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.cartmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="when_created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 5, 18, 50, 32, 223634)
            ),
        ),
    ]
