# Generated by Django 5.1.2 on 2024-11-06 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_cartmodel_when_added"),
        ("order_service", "0004_alter_ordermodel_cart_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="cart",
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="when_created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 6, 7, 55, 34, 771330)
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="cart",
            field=models.ManyToManyField(to="cart.cartmodel"),
        ),
    ]
