# Generated by Django 5.1.2 on 2024-11-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_service", "0006_alter_ordermodel_when_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="when_created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 6, 7, 56, 20, 667678)
            ),
        ),
    ]
