# Generated by Django 5.1.2 on 2024-11-04 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=30)),
                ("product_picture", models.ImageField(upload_to="product-picture/")),
                ("description", models.CharField(max_length=250, null=True)),
                ("price", models.BigIntegerField()),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("TECHNIQUE", "Technique"),
                            ("MEAL", "Meal"),
                            ("CLOTHES", "Clothes"),
                            ("BOOK", "Book"),
                            ("HOUSE", "House"),
                            ("CAR", "Car"),
                            ("BUISNES", "Buisnes"),
                            ("OTHER", "Other"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
                ("is_discount", models.BooleanField(default=False)),
                (
                    "date_of_pub",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 11, 4, 16, 13, 48, 344306)
                    ),
                ),
            ],
        ),
    ]
