# Generated by Django 5.1.2 on 2024-11-10 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_productmodel_date_of_pub"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-date_of_pub"]},
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="date_of_pub",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 10, 10, 22, 42, 646097)
            ),
        ),
    ]
