# Generated by Django 5.1.2 on 2024-11-05 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="is_ready_to_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="when_added",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 5, 7, 51, 0, 358583)
            ),
        ),
    ]
