# Generated by Django 5.1.2 on 2024-11-05 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartmodel_is_ready_to_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="when_added",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 5, 9, 22, 28, 190409)
            ),
        ),
    ]
