# Generated by Django 5.1.2 on 2024-11-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_alter_cartmodel_when_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="when_added",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 6, 7, 56, 20, 667678)
            ),
        ),
    ]
