# Generated by Django 5.1.2 on 2024-11-10 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_cartmodel_when_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartmodel",
            options={"ordering": ["-when_added"]},
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="when_added",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 10, 10, 22, 42, 691507)
            ),
        ),
    ]
